// Json data for mock suppliers and RFQs in lieu of a database or API call.
// This data was randomly generated by GPT.
export const mockRFQs = [
    {
        "id": 1,
        "client": "Precision Metalworks",
        "products": [{"productId": 1, "quantity": 2}, {"productId": 2, "quantity": 1}]
    },
    {
        "id": 2,
        "client": "Elite Machining Solutions",
        "products": [{"productId": 3, "quantity": 4}, {"productId": 2, "quantity": 1}]
    },
    {
        "id": 3,
        "client": "AeroTech Fabrications",
        "products": [{"productId": 3, "quantity": 4}, {"productId": 2, "quantity": 1}]
    },
    {
        "id": 4,
        "client": "MasterCraft Metals",
        "products": [{"productId": 1, "quantity": 3}, {"productId": 4, "quantity": 2}]
    },
    {
        "id": 5,
        "client": "Innovative Alloys",
        "products": [{"productId": 2, "quantity": 5}, {"productId": 5, "quantity": 3}]
    },
    {
        "id": 6,
        "client": "Advanced Metalworks",
        "products": [{"productId": 1, "quantity": 2}, {"productId": 3, "quantity": 1}]
    },
    {
        "id": 7,
        "client": "Superior Machining Co.",
        "products": [{"productId": 4, "quantity": 4}, {"productId": 2, "quantity": 1}]
    },
    {
        "id": 8,
        "client": "Ultimate Alloys",
        "products": [{"productId": 6, "quantity": 2}, {"productId": 3, "quantity": 3}]
    },
    {
        "id": 9,
        "client": "Prime Metal Solutions",
        "products": [{"productId": 5, "quantity": 4}, {"productId": 2, "quantity": 2}]
    },
    {
        "id": 10,
        "client": "Precision Metals Intl.",
        "products": [{"productId": 1, "quantity": 3}, {"productId": 4, "quantity": 1}]
    },
    {
        "id": 11,
        "client": "Epic Metal Fabrications",
        "products": [{"productId": 2, "quantity": 2}, {"productId": 5, "quantity": 3}]
    },
    {
        "id": 12,
        "client": "Master Alloys Inc.",
        "products": [{"productId": 1, "quantity": 4}, {"productId": 3, "quantity": 2}]
    },
    {
        "id": 13,
        "client": "Pro Metal Solutions",
        "products": [{"productId": 4, "quantity": 3}, {"productId": 2, "quantity": 1}]
    },
    {
        "id": 14,
        "client": "Precision Alloys Co.",
        "products": [{"productId": 6, "quantity": 1}, {"productId": 3, "quantity": 4}]
    },
    {
        "id": 15,
        "client": "Supreme Metalworks",
        "products": [{"productId": 5, "quantity": 2}, {"productId": 2, "quantity": 1}]
    },
    {
        "id": 16,
        "client": "Advanced Alloys Ltd.",
        "products": [{"productId": 1, "quantity": 3}, {"productId": 4, "quantity": 2}]
    },
    {
        "id": 17,
        "client": "Elite Metal Fabrications",
        "products": [{"productId": 2, "quantity": 5}, {"productId": 5, "quantity": 3}]
    },
    {
        "id": 18,
        "client": "Prime Metal Co.",
        "products": [{"productId": 1, "quantity": 2}, {"productId": 3, "quantity": 1}]
    },
    {
        "id": 19,
        "client": "Mega Metals Inc.",
        "products": [{"productId": 4, "quantity": 4}, {"productId": 2, "quantity": 1}]
    },
    {
        "id": 20,
        "client": "Ultimate Alloys Ltd.",
        "products": [{"productId": 6, "quantity": 2}, {"productId": 3, "quantity": 3}]
    },
    {
        "id": 21,
        "client": "MetalWorks Intl.",
        "products": [{"productId": 5, "quantity": 4}, {"productId": 2, "quantity": 2}]
    },
    {
        "id": 22,
        "client": "Superior Alloys",
        "products": [{"productId": 1, "quantity": 3}, {"productId": 4, "quantity": 1}]
    },
    {
        "id": 23,
        "client": "Innovative Metal Solutions",
        "products": [{"productId": 2, "quantity": 2}, {"productId": 5, "quantity": 3}]
    },
    {
        "id": 24,
        "client": "MetalTech Inc.",
        "products": [{"productId": 1, "quantity": 4}, {"productId": 3, "quantity": 2}]
    },
    {
        "id": 25,
        "client": "Pro Metal Co.",
        "products": [{"productId": 4, "quantity": 3}, {"productId": 2, "quantity": 1}]
    }
];

export const mockSuppliers = [
    {
        "id": 1,
        "name": "MetalCrafters Inc.",
        "inventory": [
            { "productId": 1, "name": "Aluminum", "price": 15, "leadTimeTemplate": "4", "quantity": 20 },
            { "productId": 2, "name": "Copper", "price": 25, "leadTimeTemplate": "6", "quantity": 15 },
            { "productId": 3, "name": "Steel", "price": 20, "leadTimeTemplate": "3", "quantity": 25 },
            { "productId": 4, "name": "Bronze", "price": 30, "leadTimeTemplate": "5", "quantity": 10 },
            { "productId": 5, "name": "Brass", "price": 28, "leadTimeTemplate": "7", "quantity": 18 },
            { "productId": 6, "name": "Titanium", "price": 35, "leadTimeTemplate": "8", "quantity": 12 }
        ]
    },
    {
        "id": 2,
        "name": "MetalTech Solutions",
        "inventory": [
            { "productId": 1, "name": "Aluminum", "price": 18, "leadTimeTemplate": "5", "quantity": 18 },
            { "productId": 2, "name": "Copper", "price": 22, "leadTimeTemplate": "4", "quantity": 22 },
            { "productId": 3, "name": "Steel", "price": 28, "leadTimeTemplate": "7", "quantity": 12 },
            { "productId": 4, "name": "Bronze", "price": 32, "leadTimeTemplate": "6", "quantity": 15 },
            { "productId": 5, "name": "Brass", "price": 26, "leadTimeTemplate": "4", "quantity": 20 },
            { "productId": 6, "name": "Titanium", "price": 38, "leadTimeTemplate": "9", "quantity": 8 }
        ]
    },
    {
        "id": 3,
        "name": "MetalWorks Ltd.",
        "inventory": [
            { "productId": 1, "name": "Aluminum", "price": 14, "leadTimeTemplate": "3", "quantity": 22 },
            { "productId": 2, "name": "Copper", "price": 20, "leadTimeTemplate": "5", "quantity": 17 },
            { "productId": 3, "name": "Steel", "price": 26, "leadTimeTemplate": "4", "quantity": 20 },
            { "productId": 4, "name": "Bronze", "price": 28, "leadTimeTemplate": "6", "quantity": 14 },
            { "productId": 5, "name": "Brass", "price": 30, "leadTimeTemplate": "8", "quantity": 18 },
            { "productId": 6, "name": "Titanium", "price": 36, "leadTimeTemplate": "7", "quantity": 10 }
        ]
    },
    {
        "id": 4,
        "name": "MetalMasters Co.",
        "inventory": [
            { "productId": 1, "name": "Aluminum", "price": 16, "leadTimeTemplate": "4", "quantity": 15 },
            { "productId": 2, "name": "Copper", "price": 24, "leadTimeTemplate": "6", "quantity": 20 },
            { "productId": 3, "name": "Steel", "price": 22, "leadTimeTemplate": "3", "quantity": 18 },
            { "productId": 4, "name": "Bronze", "price": 34, "leadTimeTemplate": "5", "quantity": 12 },
            { "productId": 5, "name": "Brass", "price": 26, "leadTimeTemplate": "7", "quantity": 16 },
            { "productId": 6, "name": "Titanium", "price": 40, "leadTimeTemplate": "8", "quantity": 14 }
        ]
    },
    {
        "id": 5,
        "name": "MetalSupplies Corp.",
        "inventory": [
            { "productId": 1, "name": "Aluminum", "price": 20, "leadTimeTemplate": "5", "quantity": 25 },
            { "productId": 2, "name": "Copper", "price": 26, "leadTimeTemplate": "4", "quantity": 15 },
            { "productId": 3, "name": "Steel", "price": 24, "leadTimeTemplate": "7", "quantity": 22 },
            { "productId": 4, "name": "Bronze", "price": 32, "leadTimeTemplate": "6", "quantity": 18 },
            { "productId": 5, "name": "Brass", "price": 30, "leadTimeTemplate": "8", "quantity": 20 },
            { "productId": 6, "name": "Titanium", "price": 38, "leadTimeTemplate": "9", "quantity": 10 }
        ]
    },
    {
        "id": 6,
        "name": "MetalForge Industries",
        "inventory": [
            { "productId": 1, "name": "Aluminum", "price": 22, "leadTimeTemplate": "6", "quantity": 18 },
            { "productId": 2, "name": "Copper", "price": 28, "leadTimeTemplate": "5", "quantity": 20 },
            { "productId": 3, "name": "Steel", "price": 30, "leadTimeTemplate": "8", "quantity": 15 },
            { "productId": 4, "name": "Bronze", "price": 36, "leadTimeTemplate": "7", "quantity": 12 },
            { "productId": 5, "name": "Brass", "price": 34, "leadTimeTemplate": "4", "quantity": 25 },
            { "productId": 6, "name": "Titanium", "price": 42, "leadTimeTemplate": "9", "quantity": 10 }
        ]
    },
    {
        "id": 7,
        "name": "MetalExpress Supply",
        "inventory": [
            { "productId": 1, "name": "Aluminum", "price": 18, "leadTimeTemplate": "4", "quantity": 22 },
            { "productId": 2, "name": "Copper", "price": 24, "leadTimeTemplate": "6", "quantity": 18 },
            { "productId": 3, "name": "Steel", "price": 28, "leadTimeTemplate": "3", "quantity": 20 },
            { "productId": 4, "name": "Bronze", "price": 30, "leadTimeTemplate": "5", "quantity": 15 },
            { "productId": 5, "name": "Brass", "price": 26, "leadTimeTemplate": "7", "quantity": 12 },
            { "productId": 6, "name": "Titanium", "price": 34, "leadTimeTemplate": "8", "quantity": 16 }
        ]
    },
    {
        "id": 8,
        "name": "MetalHarbor Solutions",
        "inventory": [
            { "productId": 1, "name": "Aluminum", "price": 20, "leadTimeTemplate": "5", "quantity": 20 },
            { "productId": 2, "name": "Copper", "price": 26, "leadTimeTemplate": "4", "quantity": 25 },
            { "productId": 3, "name": "Steel", "price": 22, "leadTimeTemplate": "6", "quantity": 18 },
            { "productId": 4, "name": "Bronze", "price": 30, "leadTimeTemplate": "8", "quantity": 15 },
            { "productId": 5, "name": "Brass", "price": 28, "leadTimeTemplate": "7", "quantity": 20 },
            { "productId": 6, "name": "Titanium", "price": 36, "leadTimeTemplate": "9", "quantity": 12 }
        ]
    },
    {
        "id": 9,
        "name": "MetalUniverse Inc.",
        "inventory": [
            { "productId": 1, "name": "Aluminum", "price": 22, "leadTimeTemplate": "4", "quantity": 18 },
            { "productId": 2, "name": "Copper", "price": 28, "leadTimeTemplate": "6", "quantity": 22 },
            { "productId": 3, "name": "Steel", "price": 26, "leadTimeTemplate": "5", "quantity": 20 },
            { "productId": 4, "name": "Bronze", "price": 34, "leadTimeTemplate": "7", "quantity": 15 },
            { "productId": 5, "name": "Brass", "price": 30, "leadTimeTemplate": "8", "quantity": 18 },
            { "productId": 6, "name": "Titanium", "price": 38, "leadTimeTemplate": "9", "quantity": 10 }
        ]
    },
    {
        "id": 10,
        "name": "MetalLink Solutions",
        "inventory": [
            { "productId": 1, "name": "Aluminum", "price": 18, "leadTimeTemplate": "5", "quantity": 15 },
            { "productId": 2, "name": "Copper", "price": 24, "leadTimeTemplate": "4", "quantity": 20 },
            { "productId": 3, "name": "Steel", "price": 30, "leadTimeTemplate": "6", "quantity": 18 },
            { "productId": 4, "name": "Bronze", "price": 32, "leadTimeTemplate": "3", "quantity": 25 },
            { "productId": 5, "name": "Brass", "price": 26, "leadTimeTemplate": "7", "quantity": 15 },
            { "productId": 6, "name": "Titanium", "price": 38, "leadTimeTemplate": "8", "quantity": 12 }
        ]
    },
];